DROP TABLE IF EXISTS Patients CASCADE;
DROP TABLE IF EXISTS Diagnose CASCADE;
DROP TABLE IF EXISTS Pharmacy CASCADE;
DROP TABLE IF EXISTS Medicine CASCADE;
DROP TABLE IF EXISTS Prescription CASCADE;
DROP TABLE IF EXISTS In_treatment_for CASCADE;
-- ROLLBACK; commit;